### ISSUE TITLE
Possibilty to assign a name to a new IP block

### ISSUE THREAD

**Issue by Sebi94nbg** [profitbricks/profitbricks-cli#10]
I miss the option to assign a name to a new IP block like it's possible in the webinterface.

        profitbricks ipblock create --location [location] --size [size] --label [label]
        profitbricks ipblock create --location de/fkb --size 1 --label "hostname-inventory-number"

Can you please add this missing parameter? Thanks!

**Comment by jasminSPC** [comment]
Currently Profitbricks API doesn't support that. See documentation here:
https://devops.profitbricks.com/api/rest/#create-ip-block

**Comment by Sebi94nbg** [comment]
Well... Do you wanna say me now, that you will implement it or not?

I'm not reporting things for fun.

**Comment by bdrung** [comment]
This feature was recently implemented in the backend and will be part of the next version of the REST API. Then the client can be extended to assign the name. You have to use the DataCenter Designer (DCD) until then to set/change the name.

**Comment by Sebi94nbg** [comment]
Thx, this was the expected answer to my question!
