### ISSUE TITLE
Possibilty to install a (Profitbricks) image on a server

### ISSUE THREAD

**Issue by Sebi94nbg** [profitbricks/profitbricks-cli#11]
Is it already possible to install a Profitbricks image like Linux Ubuntu 14.04 LTS by creating a new server? It's already possible to set a licensetype, but I believe, it's not possible to set a installer ISO/image, right?

You may can add a parameter to the volume create feature:

        profitbricks volume create --datacenterid 3fc832b1-558f-48a4-bca2-af5043975393 --size 12 --bus VIRTIO --licencetype LINUX --name "Demo Srvr 1 Boot"
        profitbricks volume create --datacenterid 3fc832b1-558f-48a4-bca2-af5043975393 --size 12 --bus VIRTIO --licencetype LINUX --name "Demo Srvr 1 Boot" --install-image linux-ubuntu-14.04-lts

But if you implement this feature, we'll also need a further parameter, which displays a list of available images. Maybe like this:

        profitbricks image [list|upload|delete|rename|install]

Images can already be listed as I saw yet:

       profitbricks image list

Following command does not work:

       profitbricks volume create --datacenterid [dcid] --size 15 --bus VIRTIO --licencetype LINUX --name "Demo Srvr 1 Boot" --imageid dc182ab0-9813-11e5-b6a2-52540066fee9

The volume will be created, but no Ubuntu 14 LTS will be installed on it.

**Comment by jasminSPC** [comment]
It is possible to create a volume with one of the existing images.

Profitbricks API doesn't allow creation of Images. Details are here: https://devops.profitbricks.com/api/rest/#images

At the end of every create|update you will get request ID at the end of the command. 
That request ID can be used to query the status of that request. There is a possibility that you used an image from a different location than the datacenter.

**Comment by Sebi94nbg** [comment]
Sorry, what?

On the one hand, you tell me, that it is possible to create a volume with an existing image and on the other hand, you tell me, that it isn't possible yet, except I would use an image from a different location than the datacenter.

Well... How I'm able to install a Linux image from an other location than the Profitbricks datacenter, if I have to tell the API the ID of the image?!

If it's possible, please document it better, that other developers understands it and please give me/us an example.

Please notice, that I was talking to the Profitbricks support and they told me, that this described issue (installing an linux image on a volume/server) isn't possible by the CLI yet. They also told me, that they have tried to create a script for me, but they weren't able to build such a script.

**Comment by edevenport** [comment]
@Sebi94nbg - I was able to successfully create a volume from an existing public image without any problems.

    profitbricks volume create --datacenterid 9e6709a0-6bf9-4bd6-8692-60349c70ce0e --size 15 --bus VIRTIO --name "Test" --imageid 157259e3-97d2-11e5-b6a2-52540066fee9

In the above command line, I had to remove --licencetype as the licence type is not necessary when you specify an existing image to use. In fact, the CLI returns the following message from the API when I mistakingly include the licence type parameter:

`[(root).properties.licenceType] Attribute must not be set if 'image' is set`

Also, as @jasminSPC stated, the datacenter referenced by the CLI must be in the same location as the image being used. In my example above, both datacenter `9e6709a0-6bf9-4bd6-8692-60349c70ce0e` and image `157259e3-97d2-11e5-b6a2-52540066fee9` were in the `us/lasdev` location.

Both `profitbricks datacenter list` and `profitbricks image list` will show the resource's location beneath the `Location` column. The location of both resources have to match. You will notice each image is listed four times; one image for each available location. For example:

    $ profitbricks image list | grep Ubuntu-15.10-server
    0b764cee-97e7-11e5-b6a2-52540066fee9  Ubuntu-15.10-server-2015-12-01                AVAILABLE  HDD   de/fra     true
    83318119-97e6-11e5-b6a2-52540066fee9  Ubuntu-15.10-server-2015-12-01                AVAILABLE  HDD   de/fkb     true
    71179507-97df-11e5-b6a2-52540066fee9  Ubuntu-15.10-server-2015-12-01                AVAILABLE  HDD   us/las     true
    78ad9179-97df-11e5-b6a2-52540066fee9  Ubuntu-15.10-server-2015-12-01                AVAILABLE  HDD   us/lasdev  true

Now, there is one caveat worth noting. There is an existing REST API bug that prevents a ProfitBricks multi-user account that is *not* the primary admin account from accessing public images. My above test succeeded because I was using my primary ProfitBricks user account. If I create another user within the DCD and attempt the same operation with that new user, then the above test will fail.

This bug affects the REST API, but not the DCD. ProfitBricks is aware of this bug and I have been told it should be fixed in the next API update which should be released soon.

**Comment by Sebi94nbg** [comment]
Thx, @edevenport ! I'll check this tomorrow. I can't remember, that the location of the images was displayed in my case and I'm also using the main account.

I'll give a feedback tomorrow. Thx in advance!

**Comment by Sebi94nbg** [comment]
@edevenport I don't get the location for the images as you can see:

        # profitbricks image list --datacenterid 545aa6cb-d4e4-4081-a3e3-2b16041be281 --location de/fkb | grep -i ubuntu | grep -i lts
        925c1c23-97db-11e5-b6a2-52540066fee9  Ubuntu-14.04-LTS-server-2015-12-01                    2015-12-01T03:28:21Z  AVAILABLE
        8fe38ce7-97d9-11e5-b6a2-52540066fee9  Ubuntu-12.04-LTS-server-2015-12-01                    2015-12-01T03:13:58Z  AVAILABLE
        51775363-97d9-11e5-b6a2-52540066fee9  Ubuntu-12.04-LTS-server-2015-12-01                    2015-12-01T03:12:13Z  AVAILABLE
        b8b476c9-97d9-11e5-b6a2-52540066fee9  Ubuntu-12.04-LTS-server-2015-12-01                    2015-12-01T03:15:06Z  AVAILABLE
        8b2f68d1-97db-11e5-b6a2-52540066fee9  Ubuntu-14.04-LTS-server-2015-12-01                    2015-12-01T03:28:09Z  AVAILABLE
        89270085-97d9-11e5-b6a2-52540066fee9  Ubuntu-12.04-LTS-server-2015-12-01                    2015-12-01T03:13:46Z  AVAILABLE
        53c8fe98-9813-11e5-b6a2-52540066fee9  Ubuntu-14.04-LTS-server-2015-12-01                    2015-12-01T10:07:28Z  AVAILABLE
        dc182ab0-9813-11e5-b6a2-52540066fee9  Ubuntu-14.04-LTS-server-2015-12-01                    2015-12-01T10:11:16Z  AVAILABLE
        1087680b-6cc3-11e5-b680-52540066fee9  Bacula-8.2.7-EE-Ubuntu-14.04-LTS                      2015-10-07T07:14:35Z  AVAILABLE
        77ea2eaf-6da7-11e5-b680-52540066fee9  Bacula-8.2.7-EE-Ubuntu-14.04-LTS                      2015-10-08T10:29:34Z  AVAILABLE
        6cc1511c-6da8-11e5-b680-52540066fee9  Bacula-8.2.7-EE-Ubuntu-14.04-LTS                      2015-10-08T10:36:25Z  AVAILABLE
        f6b87d47-6da7-11e5-b680-52540066fee9  Bacula-8.2.7-EE-Ubuntu-14.04-LTS                      2015-10-08T10:33:07Z  AVAILABLE
        
        # profitbricks image list --datacenterid 545aa6cb-d4e4-4081-a3e3-2b16041be281 | grep -i ubuntu | grep -i lts
        925c1c23-97db-11e5-b6a2-52540066fee9  Ubuntu-14.04-LTS-server-2015-12-01                    2015-12-01T03:28:21Z  AVAILABLE
        8fe38ce7-97d9-11e5-b6a2-52540066fee9  Ubuntu-12.04-LTS-server-2015-12-01                    2015-12-01T03:13:58Z  AVAILABLE
        51775363-97d9-11e5-b6a2-52540066fee9  Ubuntu-12.04-LTS-server-2015-12-01                    2015-12-01T03:12:13Z  AVAILABLE
        b8b476c9-97d9-11e5-b6a2-52540066fee9  Ubuntu-12.04-LTS-server-2015-12-01                    2015-12-01T03:15:06Z  AVAILABLE
        8b2f68d1-97db-11e5-b6a2-52540066fee9  Ubuntu-14.04-LTS-server-2015-12-01                    2015-12-01T03:28:09Z  AVAILABLE
        89270085-97d9-11e5-b6a2-52540066fee9  Ubuntu-12.04-LTS-server-2015-12-01                    2015-12-01T03:13:46Z  AVAILABLE
        53c8fe98-9813-11e5-b6a2-52540066fee9  Ubuntu-14.04-LTS-server-2015-12-01                    2015-12-01T10:07:28Z  AVAILABLE
        dc182ab0-9813-11e5-b6a2-52540066fee9  Ubuntu-14.04-LTS-server-2015-12-01                    2015-12-01T10:11:16Z  AVAILABLE
        1087680b-6cc3-11e5-b680-52540066fee9  Bacula-8.2.7-EE-Ubuntu-14.04-LTS                      2015-10-07T07:14:35Z  AVAILABLE
        77ea2eaf-6da7-11e5-b680-52540066fee9  Bacula-8.2.7-EE-Ubuntu-14.04-LTS                      2015-10-08T10:29:34Z  AVAILABLE
        6cc1511c-6da8-11e5-b680-52540066fee9  Bacula-8.2.7-EE-Ubuntu-14.04-LTS                      2015-10-08T10:36:25Z  AVAILABLE
        f6b87d47-6da7-11e5-b680-52540066fee9  Bacula-8.2.7-EE-Ubuntu-14.04-LTS                      2015-10-08T10:33:07Z  AVAILABLE
        
        # profitbricks image list | grep -i ubuntu | grep -i lts
        925c1c23-97db-11e5-b6a2-52540066fee9  Ubuntu-14.04-LTS-server-2015-12-01                    2015-12-01T03:28:21Z  AVAILABLE
        8fe38ce7-97d9-11e5-b6a2-52540066fee9  Ubuntu-12.04-LTS-server-2015-12-01                    2015-12-01T03:13:58Z  AVAILABLE
        51775363-97d9-11e5-b6a2-52540066fee9  Ubuntu-12.04-LTS-server-2015-12-01                    2015-12-01T03:12:13Z  AVAILABLE
        b8b476c9-97d9-11e5-b6a2-52540066fee9  Ubuntu-12.04-LTS-server-2015-12-01                    2015-12-01T03:15:06Z  AVAILABLE
        8b2f68d1-97db-11e5-b6a2-52540066fee9  Ubuntu-14.04-LTS-server-2015-12-01                    2015-12-01T03:28:09Z  AVAILABLE
        89270085-97d9-11e5-b6a2-52540066fee9  Ubuntu-12.04-LTS-server-2015-12-01                    2015-12-01T03:13:46Z  AVAILABLE
        53c8fe98-9813-11e5-b6a2-52540066fee9  Ubuntu-14.04-LTS-server-2015-12-01                    2015-12-01T10:07:28Z  AVAILABLE
        dc182ab0-9813-11e5-b6a2-52540066fee9  Ubuntu-14.04-LTS-server-2015-12-01                    2015-12-01T10:11:16Z  AVAILABLE
        1087680b-6cc3-11e5-b680-52540066fee9  Bacula-8.2.7-EE-Ubuntu-14.04-LTS                      2015-10-07T07:14:35Z  AVAILABLE
        77ea2eaf-6da7-11e5-b680-52540066fee9  Bacula-8.2.7-EE-Ubuntu-14.04-LTS                      2015-10-08T10:29:34Z  AVAILABLE
        6cc1511c-6da8-11e5-b680-52540066fee9  Bacula-8.2.7-EE-Ubuntu-14.04-LTS                      2015-10-08T10:36:25Z  AVAILABLE
        f6b87d47-6da7-11e5-b680-52540066fee9  Bacula-8.2.7-EE-Ubuntu-14.04-LTS                      2015-10-08T10:33:07Z  AVAILABLE

Can you please provide me the image-id of the _Ubuntu-14.04-LTS-server-2015-12-01_ image at the location _de/fkb_? Thanks!

**Comment by jasminSPC** [comment]
Here is the ID you requested
```53c8fe98-9813-11e5-b6a2-52540066fee9  Ubuntu-14.04-LTS-server-2015-12-01 AVAILABLE  HDD   de/fkb     true```

It seems you are using an older version of the CLI. Current version is 
```profitbricks --version
1.1.1```
Can you please update your npm package by doing this:
```npm update -g profitbricks-cli```

I hope this helps

**Comment by Sebi94nbg** [comment]
Oh, lol. :D

Yes, there was an older version installed:

        # profitbricks --version
        0.0.1

I've updated the CLI with your command, but some files couldn't be fetched and returned an error. Hope, it doesn't matter.

        npm ERR! fetch failed https://registry.npmjs.org/request/-/request-2.67.0.tgz
        npm ERR! fetch failed https://registry.npmjs.org/request/-/request-2.67.0.tgz
        npm ERR! fetch failed https://registry.npmjs.org/is-typedarray/-/is-typedarray-1.0.0.tgz
        npm ERR! fetch failed https://registry.npmjs.org/is-typedarray/-/is-typedarray-1.0.0.tgz
        npm ERR! fetch failed https://registry.npmjs.org/once/-/once-1.3.3.tgz

By re-running the command, it just returns following:

        npm http GET https://registry.npmjs.org/profitbricks-cli
        npm http 304 https://registry.npmjs.org/profitbricks-cli

Great! Now I also can see the locations of the images. Nice! :)

        # profitbricks image list --datacenterid 545aa6cb-d4e4-4081-a3e3-2b16041be281 --location de/fkb | grep -i ubuntu | grep -i lts
        925c1c23-97db-11e5-b6a2-52540066fee9  Ubuntu-14.04-LTS-server-2015-12-01  AVAILABLE  HDD   us/lasdev  true
        8fe38ce7-97d9-11e5-b6a2-52540066fee9  Ubuntu-12.04-LTS-server-2015-12-01  AVAILABLE  HDD   us/lasdev  true
        51775363-97d9-11e5-b6a2-52540066fee9  Ubuntu-12.04-LTS-server-2015-12-01  AVAILABLE  HDD   de/fkb     true
        b8b476c9-97d9-11e5-b6a2-52540066fee9  Ubuntu-12.04-LTS-server-2015-12-01  AVAILABLE  HDD   de/fra     true
        8b2f68d1-97db-11e5-b6a2-52540066fee9  Ubuntu-14.04-LTS-server-2015-12-01  AVAILABLE  HDD   us/las     true
        89270085-97d9-11e5-b6a2-52540066fee9  Ubuntu-12.04-LTS-server-2015-12-01  AVAILABLE  HDD   us/las     true
        53c8fe98-9813-11e5-b6a2-52540066fee9  Ubuntu-14.04-LTS-server-2015-12-01  AVAILABLE  HDD   de/fkb     true
        dc182ab0-9813-11e5-b6a2-52540066fee9  Ubuntu-14.04-LTS-server-2015-12-01  AVAILABLE  HDD   de/fra     true
        1087680b-6cc3-11e5-b680-52540066fee9  Bacula-8.2.7-EE-Ubuntu-14.04-LTS    AVAILABLE  HDD   us/lasdev  true
        77ea2eaf-6da7-11e5-b680-52540066fee9  Bacula-8.2.7-EE-Ubuntu-14.04-LTS    AVAILABLE  HDD   us/las     true
        6cc1511c-6da8-11e5-b680-52540066fee9  Bacula-8.2.7-EE-Ubuntu-14.04-LTS    AVAILABLE  HDD   de/fra     true
        f6b87d47-6da7-11e5-b680-52540066fee9  Bacula-8.2.7-EE-Ubuntu-14.04-LTS    AVAILABLE  HDD   de/fkb     true

Just one question regarding this: Why is it not possible to filter for images just in the location like in my example above? The parameter/option "--location de/fkb" has no effect on the command, but also doesn't return an error message or something else.

**Comment by jasminSPC** [comment]
I'm glad I could help.

Currently ProfitBricks API doesn't support filtering images by any parameter. I believe this is planned to be released soon.

**Comment by Sebi94nbg** [comment]
Great and thanks for the support!

        # profitbricks volume create --datacenterid 545aa6cb-d4e4-4081-a3e3-2b16041be281 --size 15 --bus VIRTIO --name "p-v00321-boot" --imageid 53c8fe98-9813-11e5-b6a2-52540066fee9 --json
        [{"Id":"7baca292-d411-495c-b880-235a5674484a","Name":"p-v00321-boot","Size":15,"Licence":null,"Bus":"VIRTIO","State":"BUSY"}]
        RequestID: c268e736-26e2-4f98-a7e8-8b9f249c8fff

One last question regarding this topic. For what are the request IDs? What can I do with them?

**Comment by jasminSPC** [comment]
The "RequestID" that was returned can be used to check on the status of any create or update operations.

```profitbricks request get -i [RequestId]
Status: DONE
Message: Request has been successfully executed```

**Comment by Sebi94nbg** [comment]
Ah, ok. Thanks for the information!

        # profitbricks request get -i c268e736-26e2-4f98-a7e8-8b9f249c8fff
        Status: DONE
        Message: Request has been successfully executed

#closed
