### ISSUE TITLE
Possibilty to list available locations

### ISSUE THREAD

**Issue by Sebi94nbg** [profitbricks/profitbricks-cli#12]
In your REST API it's possible to get a list of available locations: https://devops.profitbricks.com/api/rest/#locations

Can you please add this as further parameter to the CLI? Maybe like this:

        profitbricks location list

I think more options/parameters aren't needed for locations, because customers can't add or remove locations. Well... They just want to see, which locations exists with a few information (eg. location id).

Location | ID
:------------- | :-------------
Europe / Germany / Frankfurt | de/fra
Europe / Germany / Karlsruhe | de/fkb
North America / USA / Las Vegas | us/las

**Comment by jasminSPC** [comment]
`profitbricks location list`
Version 1.1.16
Locations
--------------------
Id         Name
---------  ---------
de/fkb     karlsruhe
de/fra     frankfurt
us/las     lasvegas
us/lasdev  developer

**Comment by Sebi94nbg** [comment]
Nice, thanks! :+1:
