### ISSUE TITLE
Unable to update NIC

### ISSUE THREAD

**Issue by Sebi94nbg** [profitbricks/profitbricks-cli#13]
I've the problem, that I can't update my NICs due a code issue in the following file:

        /usr/local/lib/node_modules/profitbricks-cli/features/nic.js:91

It's missing following line above "try {":

        var data = {}

The error message is following:

        # profitbricks --datacenterid [dcid] nic update --serverid [serverid] -i 058baf2e-0cce-487d-859f-2606ff3e3166 --ip 10.40.1.90
        
        /usr/local/lib/node_modules/profitbricks-cli/features/nic.js:109
                pbclient.patchNic(params.datacenterid, params.serverid, data, helpers.
                                                                        ^
        ReferenceError: data is not defined
            at updateNic (/usr/local/lib/node_modules/profitbricks-cli/features/nic.js:109:65)
            at Object.processNic [as process] (/usr/local/lib/node_modules/profitbricks-cli/features/nic.js:43:13)
            at parseParameters (/usr/local/lib/node_modules/profitbricks-cli/profitbricks.js:149:13)
            at Object.<anonymous> (/usr/local/lib/node_modules/profitbricks-cli/profitbricks.js:29:1)
            at Module._compile (module.js:456:26)
            at Object.Module._extensions..js (module.js:474:10)
            at Module.load (module.js:356:32)
            at Function.Module._load (module.js:312:12)
            at Module.require (module.js:364:17)
            at require (module.js:380:17)

But this also didn't fixed my issue. There is still an other issue, which I couldn't fix:

        $ profitbricks nic list --datacenterid [dcid] --serverid [serverid]
        Nics
        -----------------------------------------------------------------------------------
        Id                                    Name          Created               State
        ------------------------------------  ------------  --------------------  ---------
        ea1c54c9-a568-4a7e-8aca-c7ba463c1216  p-v00321-nic  2015-12-04T13:18:02Z  AVAILABLE
        
        $ profitbricks nic update --datacenterid [dcid] -i ea1c54c9-a568-4a7e-8aca-c7ba463c1216 --serverid [serverid] --ip 10.40.1.80
        Status: 404
        Headers: {"date":"Fri, 04 Dec 2015 13:56:56 GMT","server":"\"\"","pragma":"No-cache","cache-control":"no-cache","expires":"Thu, 01 Jan 1970 00:00:00 UTC","x-ratelimit-remaining":"49","x-ratelimit-burst":"50","x-ratelimit-limit":"120","content-type":"application/vnd.profitbricks.error+json","strict-transport-security":"max-age=15768000","keep-alive":"timeout=5, max=100","connection":"Keep-Alive","transfer-encoding":"chunked"}
        Body {
          "httpStatus" : 404,
          "messages" : [ {
            "errorCode" : "309",
            "message" : "Resource does not exist"
          } ]
        }

Please note, that I've censored the datacenter and server ID.

**Comment by Sebi94nbg** [comment]
With the latest profitbricks-cli version 1.1.7 I just get this error message:

        # profitbricks -V
        1.1.7
        
        # profitbricks --datacenterid 545aa6cb-d4e4-4081-a3e3-2b16041be281 nic list --serverid e2abb7b7-10f2-4be3-8571-414c3bdbb860
        Nics
        -----------------------------------------------------------------------------------------------------------------------
        Id                                    Name          Created               State      Lan  Mac                Ips
        ------------------------------------  ------------  --------------------  ---------  ---  -----------------  ----------
        475c76aa-b016-4012-8461-62478df0923c  p-v00321-nic  2015-12-16T09:14:41Z  AVAILABLE  1    02:01:e5:45:8c:d2  10.40.1.90
        
        # profitbricks --datacenterid 545aa6cb-d4e4-4081-a3e3-2b16041be281 nic update --serverid e2abb7b7-10f2-4be3-8571-414c3bdbb860 -i 475c76aa-b016-4012-8461-62478df0923c --ip 10.40.1.84
        { properties: { name: [Function], ips: [ '10.40.1.84' ] } }
        { errorcode: 400,
          errormsg: '{\n  "httpStatus" : 400,\n  "messages" : [ {\n    "errorCode" : "304",\n    "message" : "Failed to parse request body. [line: 1, column: 16] Unrecognized field \'properties\'"\n  } ]\n}\n' }

**Comment by edevenport** [comment]
@Sebi94nbg - I found a bug in the `nic update` code and @jasminSPC was able to issue a fix and release a new package. If you update profitbricks-cli to the latest, 1.1.8, it should correct the issue you describe above.

**Comment by Sebi94nbg** [comment]
Thanks for the fix!
