### ISSUE TITLE
permissions .auth file

### ISSUE THREAD

**Issue by uwebartels** [profitbricks/profitbricks-cli#14]
Hiho,

when running the initial 'profitbricks setup' -  my credentials as stored in a file with permissions 644. So everybody can read them and decode on the server. please fix.

Thanks.
Uwe

**Comment by Sebi94nbg** [comment]
+1

Is it possible to check with which credentials the profitbricks-cli is/was installed and configured? It's maybe helpful to get just the username/e-mail address of the account, that the user can check this for support cases or configuration changes.

**Comment by uwebartels** [comment]
Hi,

I was using the root account on the linux machine and my personal 
account uwe.bartels@cloud.exchange for profitbricks authentication.

Best...
Uwe

Uwe Bartels
Systemarchitect - Databasespecialist - Freelancer
mailto: uwe.bartels@posteo.de
tel: +49 151 64316810
profile: https://www.xing.com/profile/Uwe_Bartels
website: http://www.uwebartels.com

**Comment by Sebi94nbg** [comment]
Ah, ok.

> After successful authentication you will no longer need to provide credentials unless you want to change them. They are stored as a *BASE64 encoded string in a '.auth' file in your home directory*.

This is very easy to decode, as you can see here:

        $ cat ~/.auth | base64 --decode
        your.email@example.com:very$Secr8tPas5w0Rd!

I agree with @uwebartels , that it's unsecure and should be more safer.

**Comment by uwebartels** [comment]
Regarding the base64 I don't mind. This is OK as you need to decode it 
anyway.

But everybody can read this file by default. File mode 0644.
And there is no hint, that the file is created.
And .auth as a filename can by anything, better would be a place like 
~/.profitbricks_auth or whatever corresponds to the library.

Best Regards,
Uwe

Uwe Bartels
Systemarchitect - Databasespecialist - Freelancer
mailto: uwe.bartels@posteo.de
tel: +49 151 64316810
profile: https://www.xing.com/profile/Uwe_Bartels
website: http://www.uwebartels.com

**Comment by jasminSPC** [comment]
Please update to version 1.1.10
.auth file is now set to in my case

```-rw------- 1 jasmin jasmin 48 Jan 15 00:29 .auth```
