### ISSUE TITLE
Add / Remove single IPs by using 'nic update'

### ISSUE THREAD

**Issue by Sebi94nbg** [profitbricks/profitbricks-cli#20]
As already discussed with @jasminSPC yesterday, _nic update_ has a little issue.

        profitbricks nic update --datacenterid [dcid] --serverid [server_id] --id [nic_id] --ip 123.123.123.123

The above mentioned command is causing very much trouble, because it's updating *all* IPs on this NIC to the given one from this command. This means, if you have this IPs set for example:

        Primary IP: 123.7.93.100
        
        Additional IP: 251.123.321.168
        Additional IP: 251.123.321.222
        Additional IP: 78.127.123.111
        Additional IP: 46.78.79.13
        Additional IP: 78.127.123.9

...the command would remove all IPs and just set the new primary IP _123.123.123.123_:

        Primary IP: 123.123.123.123

This is fatal and can cause a downtime for multiple server, if the updated server is/was a router/firewall, which use NAT to forward all requests to the correct server. In my scenario for example, I've "shutdown" the full datacenter of my company for about 30 minutes.

The issue is caused by the REST API of Profitbricks, because the _NIC update_ part requires a collection of IPs and not only a single IP: https://devops.profitbricks.com/api/rest/#update-a-nic

Well... Currently you have to get the list of all assigned IPs, add or remove your wanted IP from or to this list and run the _nic update_ command on the CLI. Great... NOT!

I've already asked @jasminSPC , if you can add two further parameters to the CLI, which are doing this automatic. For example:

        profitbricks nic [update|add|remove]

_Update_ should do something like updating the NIC or an IP, while _add_ and _remove_ should do how it's called for: Adding and removing something - in thise case *single* IPs. Following the logic, which I've already sent to @jasminSPC as file:

```javascript

// Get list of assigned/set IPs
function getListOfSetIP(params) {
	var ipBlockList = processIpblock(list) // Save a current list of the IP Block(s)
	
	return ipBlockList
}

// Adds a further IP to NIC
function addIPtoNIC(params) {
    var ipBlockList = getListOfSetIP(params.datacenterid, params.serverid, params.id) // Call function to get current IP Block list
	
	var data = {}
    try {
        if (params.path) {
            data = JSON.parse(fs.readFileSync(params.path, 'utf8'))
        }
        else {
            data = {}
            if (params.name)
                data.name = params.name
            if (params.ip)
                data.ips = ipBlockList . [params.ip] // Append new/further IP to existing IP Block
        }
    }
    finally {
        pbclient.patchNic(params.datacenterid, params.serverid, params.id, data, helpers.printInfo)
    }
}

// Removes a single IP from NIC
function delIPfromNIC(params) {
    var ipBlockList = getListOfSetIP(params.datacenterid, params.serverid, params.id) // Call function to get current IP Block list
	ipBlockList = str_replace([params.ip], "", ipBlockList) // Remove IP Block from list
	
	var data = {}
    try {
        if (params.path) {
            data = JSON.parse(fs.readFileSync(params.path, 'utf8'))
        }
        else {
            data = {}
            if (params.name)
                data.name = params.name
            if (params.ip)
                data.ips = ipBlockList
        }
    }
    finally {
        pbclient.patchNic(params.datacenterid, params.serverid, params.id, data, helpers.printInfo)
    }
}
```

@jasminSPC has already contacted Profitbricks, to ask them, if there is an better solution for this problem or if they can implement something better for this to not slow down the CLI.

I'm waiting for the fix, thanks in advance!

**Comment by Sebi94nbg** [comment]
Any updates, @jasminSPC ?

**Comment by jasminSPC** [comment]
Nothing at the moment. I will keep you posted

On Mon, Jan 25, 2016 at 8:18 PM, TS3tools <notifications@github.com> wrote:

> Any updates, @jasminSPC <https://github.com/jasminSPC> ?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/profitbricks/profitbricks-cli/issues/20#issuecomment-174626869>
> .
>



-- 
Jasmin Gacić

**Comment by jasminSPC** [comment]
You can achieve this by running one of following:

`profitbricks nic update --datacenterid [dc] --serverid [server] -i [nicid] --addip 1.1.1.1 `
`profitbricks nic update --datacenterid [dc] --serverid [server] -i [nicid] --removeip 1.1.1.1 `

**Comment by Sebi94nbg** [comment]
Thanks, I'll test it!
