### ISSUE TITLE
CHANGELOG missing

### ISSUE THREAD

**Issue by Sebi94nbg** [profitbricks/profitbricks-cli#22]
Please add a changelog to the repository, which provides the made changes, that everybody can see what has been changed between version 1.1.10 and 1.1.11 for example.

Here is an example from me: https://github.com/TS3Tools/TS3UpdateScript/blob/master/docs/CHANGELOG.md

**Comment by jasminSPC** [comment]
We will look into it.

**Comment by Sebi94nbg** [comment]
Great, thanks! :)

**Comment by jasminSPC** [comment]
https://github.com/profitbricks/profitbricks-cli/releases/tag/1.1.16

There you go

**Comment by Sebi94nbg** [comment]
Thanks! :+1:
