### ISSUE TITLE
--availabilityzone parameter causes the request to fail

### ISSUE THREAD

**Issue by botchniaque** [profitbricks/profitbricks-cli#23]
$ profitbricks server update --datacenterid f0470b4e-3275-440c-ab48-ce90fdfc2ea8 -i 59b02d15-54c5-4786-8125-92cacdc61e5e --availabilityzone ZONE_1

    { errorcode: 400, errormsg: '{\n  "httpStatus" : 400,\n  "messages" : [ {\n    "errorCode" : "304"," : "Failed to parse request body. [line: 1, column: 22] Unrecognized field \'availabilityzone\'"\n  } ]\n}\n' }

**Comment by jasminSPC** [comment]
Does this PR https://github.com/profitbricks/profitbricks-cli/pull/24 fix
this issue?

On Mon, Jan 25, 2016 at 1:20 PM, Szymon Bochniak <notifications@github.com>
wrote:

> $ profitbricks server update --datacenterid f0470b4e-3275-440c-ab48-ce90fdfc2ea8 -i 59b02d15-54c5-4786-8125-92cacdc61e5e --availabilityzone ZONE_1
>
> { errorcode: 400, errormsg: '{\n  "httpStatus" : 400,\n  "messages" : [ {\n    "errorCode" : "304"," : "Failed to parse request body [line: 1, column: 22] Unrecognized field \'availabilityzone\'"\n  } ]\n}\n' }
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/profitbricks/profitbricks-cli/issues/23>.
>



-- 
Jasmin Gacić

**Comment by botchniaque** [comment]
Yes, I have tested it locally and I was able to update the zone using `--availabilityzone` cli parameter

**Comment by jasminSPC** [comment]
Ok I will go ahead and merge the PR and close the issue.

On Mon, Jan 25, 2016 at 1:27 PM, Szymon Bochniak <notifications@github.com>
wrote:

> Yes, I have tested it locally and I was able to update the zone using
> --availabilityzone cli parameter
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/profitbricks/profitbricks-cli/issues/23#issuecomment-174490877>
> .
>



-- 
Jasmin Gacić

**Comment by jasminSPC** [comment]
npm package  + profitbricks-cli@1.1.12
