### ISSUE TITLE
CLI returns no such file or directory for version parameter in version 1.1.12

### ISSUE THREAD

**Issue by Sebi94nbg** [profitbricks/profitbricks-cli#26]
Something is corrupt...

        # npm update -g profitbricks-cli 1.1.12
        npm http GET https://registry.npmjs.org/profitbricks-cli
        npm http 304 https://registry.npmjs.org/profitbricks-cli
        
        # profitbricks -V
        : No such file or directory

**Comment by botchniaque** [comment]
I have to confirm that I was getting the same problem with older versions as well after an update.
My workaround was to call it via node:

    /usr/local/lib/node_modules/profitbricks-cli$ node profitbricks.js datacenter list


So I assume the update procedure messes up with links or something.

**Comment by jasminSPC** [comment]
I'm looking into it

On Tue, Jan 26, 2016 at 10:58 AM, Szymon Bochniak <notifications@github.com>
wrote:

> I have to confirm that I was getting the same problem with older versions
> as well after an update.
> My workaround was to call it via node:
>
> /usr/local/lib/node_modules/profitbricks-cli$ node profitbricks.js datacenter list
>
> So I assume the update procedure messes up with links or something.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/profitbricks/profitbricks-cli/issues/26#issuecomment-174935305>
> .
>



-- 
Jasmin Gacić

**Comment by jasminSPC** [comment]
So I just did this:

   >$ profitbricks -V
   >1.1.12
   >$ profitbricks datacenter list
   >Datacenters
   >------------------------------------------------------
   >Id                                    Name    Location
   >------------------------------------  ------  --------
   >b0ac144e-e294-415f-ba39-6737d5a9d419  docker  us/las

On windows I was getting a similar error but after restarting the console it all cleared up

   >C:\Users\jasmin.gacic>npm update -g profitbricks-cli 1112

   >C:\Users\jasmin.gacic>projects -V

   >C:\Users\jasmin.gacic>profitbricks -V
   >1.1.12

Perhaps try restarting the bash/console after the update. 
Also my current version of npm is at on windows 3.3.12 and on ubuntu 3.5.3 you can achieve that by running ***npm install -g npm@latest***

**Comment by Sebi94nbg** [comment]
Upgrading npm to the latest version and restarting the console didn't helped. I'm still getting the no such file or directory message.

**Comment by jasminSPC** [comment]
Can you do this
>npm uninstall -g profitbricks-cli
and then
>npm install -g profitbricks-cli

**Comment by Sebi94nbg** [comment]
Done and worked fine, but the issue is still not fixed.

**Comment by jasminSPC** [comment]
@botchniaque your latest commit https://github.com/profitbricks/profitbricks-cli/commit/416d43d2304ae14b19ef641925392383b60b7180 has changed file mode for profitbricks file.

**Comment by botchniaque** [comment]
Oops, sorry then. That would explain why I was having the issue before - must have messed up.

**Comment by Sebi94nbg** [comment]
Thanks, the new version 1.1.14 solved the issue a bit confusing:

        # npm update -g profitbricks-cli 1.1.14
        .
        .
        .
        # profitbricks -V
        1.1.15

**Comment by jasminSPC** [comment]
I'm glad it helped. 

When I published the npm package the code and npm version were not in sync. So I published it one more time and now it is at version 1.1.15. If it is bothering you too much just do npm install -g profitbricks-cli@latest
