### ISSUE TITLE
Profitbricks Setup does not work properly

### ISSUE THREAD

**Issue by gitfvb** [profitbricks/profitbricks-cli#30]
Hi,

When using the CLI and type "profitbricks setup" I can enter the username but after pressing Enter the CLI does not give me the chance to enter the password. It says directly the password is incorrect.

Another question: Is two-factor-auth supported in the CLI?

Thanks

Florian

**Comment by jasminSPC** [comment]
Can you send me the CLI version you are using at the moment by running
profitbricks --version.

Two factor auth is not supported in the CLI at the moment.

On Thu, Jan 28, 2016 at 2:51 PM, Florian von Bracht <
notifications@github.com> wrote:

> Hi,
>
> When using the CLI and type "profitbricks setup" I can enter the username
> but after pressing Enter the CLI does not give me the chance to enter the
> password It says directly the password is incorrect
>
> Another question: Is two-factor-auth supported in the CLI?
>
> Thanks
>
> Florian
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/profitbricks/profitbricks-cli/issues/30>.
>



-- 
Jasmin Gacić

**Comment by jasminSPC** [comment]
I've just ran the setup command in ubuntu and I got this:

~$ profitbricks -V
1.1.15
~$ profitbricks setup
prompt: username:  *******
prompt: password:  
~$ profitbricks datacenter list
Datacenters
-----------------------------------------------------------------------------------
Id                                    Name                                Location 
------------------------------------  ----------------------------------  ---------
d3c13a5e-46b0-4ddb-b255-f4d17166f54d  Widget Corporation:developer        us/las

And in windows too:

C:\>profitbricks -V
1.1.15

C:>profitbricks setup
prompt: username:  *******
prompt: password:

C:\>profitbricks datacenter list
Datacenters
-----------------------------------------------------------------------------------
Id                                    Name                                Location
------------------------------------  ----------------------------------  ---------
cfd851a6-c4bb-4ab1-97bc-159ed6aba2fe  Ruby SDK Datacenter                 de/fkb

**Comment by gitfvb** [comment]
Thank you for the quick reaction. You can see my problem in this video:
[https://www.dropbox.com/s/i8406sillwaop0n/TinyTake%20by%20MangoApps-28-01-2016-06-35-34.mp4?dl=0](url)

**Comment by jasminSPC** [comment]
Could you try reinstall the cli but running 
*npm uninstall -g profitbricks-cli*

**Comment by gitfvb** [comment]
That problem is still there... I had a look into the code and it seems to be a bug in the prompt-thing. Maybe it has to do with Win10.

I realized... When I press Enter when it prompts the username the first time... Then the login is incorrect and it asks again for the username.... After that it works properly :-)

What I also realized... This is some kind of security gap, that the 2factor-auth is not working.

**Comment by jasminSPC** [comment]
I will look into it. I also tested it on win 10 and haven't had that
problem.

But I will keep on looking.

**Comment by jasminSPC** [comment]
There seems to be an issue with the prompt library that we are using.
Someone suggested (https://github.com/flatiron/prompt/issues/131) that
upgrading nodejs to version 5.5.0 should help.
Nodejs 5.5.0 can be found here:
https://nodejs.org/en/download/stable/

Also it seems using gitbash in Windows 10 helps with this issue.

Let me know if this helps

On Fri, Jan 29, 2016 at 2:33 PM, Jasmin Gacic <jasmin@stackpointcloud.com>
wrote:

> I will look into it. I also tested it on win 10 and haven't had that
> problem.
>
> But I will keep on looking.
> On Jan 29, 2016 13:37, "Florian von Bracht" <notifications@github.com>
> wrote:
>
>> That problem is still there... I had a look into the code and it seems to
>> be a bug in the prompt-thing. Maybe it has to do with Win10.
>>
>> I realized... When I press Enter when it prompts the username the first
>> time... Then the login is incorrect and it asks again for the username....
>> After that it works properly :-)
>>
>> What I also realized... This is some kind of security gap, that the
>> 2factor-auth is not working.
>>
>> —
>> Reply to this email directly or view it on GitHub
>> <https://github.com/profitbricks/profitbricks-cli/issues/30#issuecomment-176731863>
>> .
>>
>


-- 
Jasmin Gacić

**Comment by jasminSPC** [comment]
@gitfvb was the issue resloved?

**Comment by gitfvb** [comment]
Hi,

Thank you so much for your help. Yes, you can close the issue.

Cheers

Florian



Am 01.02.2016 um 13:44 schrieb jasminSPC:
