### ISSUE TITLE
Changes in the cli

### ISSUE THREAD

**Issue by koboltmarky** [profitbricks/profitbricks-cli#39]
Hi,

before one of the last updates i can change a network interface with:

`profitbricks nic update  -i XXXXX --name test  --datacenterid XXXXX --serverid XXX --dhcp false --lan 3 --json`

now:

`profitbricks nic update  -i XXXXX --removeip --name test  --datacenterid XXXXX --serverid XXX --dhcp false --lan 3 --json`

Is `--removeip` now required ?

Greets 
Marc

**Comment by koboltmarky** [comment]
And Output DA DA is really not helpful.

**Comment by jasminSPC** [comment]
Sorry for that DA DA was a debug message that was not removed after testing.

As for the removeid param it is not required for update, but I did find a bug that I removed with version 1.2.5

please update your cli with ```npm install profitbricks-cli@latest -g ```

**Comment by koboltmarky** [comment]
I use:
1.2.4
I think this is the latest. We have some deployment scripts and the command worked before the update.
Now i'm getting no error message only "DA DA" but dhcp isn't disabled.

**Comment by jasminSPC** [comment]
I just pushed latest version which is 1.2.5
I also ran this:

```$ profitbricks nic update --datacenterid f83be52c-1936-4fe1-b5d6-82fb8ec96060 --serverid 344cfd1f-35b9-449c-a75c-07127e1f593a -i 70a64cd4-fa86-4189-ac9f-c21dc37a086a --name test1 --dhcp false```

and I can see that dhcp was disabled on this specific NIC

{
        "id" : "70a64cd4-fa86-4189-ac9f-c21dc37a086a",
        "type" : "nic",
        "href" : "https://api.profitbricks.com/rest/datacenters/f83be52c-1936-4fe1-b5d6-82fb8ec96060/servers/344cfd1f-35b9-449c-a75c-07127e1f593a/nics/70a64cd4-fa86-4189-ac9f-c21dc37a086a",
        "properties" : {
          "name" : "test1",
          "mac" : "02:01:41:d2:ed:45",
          "ips" : [ "10.13.52.11" ],
         ** "dhcp" : false,**

**Comment by koboltmarky** [comment]
It works.
