### ISSUE TITLE
CHANGELOG missing

### ISSUE THREAD

**Issue by Sebi94nbg** [profitbricks/profitbricks-cli#42]
Again, your CHANGELOG is missing and/or outdated. I want to know, what's the current latest version and what has been changed in the new releases, that I can decide, if I want to update the CLI or not.

You closed the issue #22, because you've created [some releases](https://github.com/profitbricks/profitbricks-cli/releases) with a changelog. That was OK for me and it corresponded my expectations.

If you don't add an explicit changelog file, please always create a new release with the version string and the changes in this version. If you don't create such releases, please care a changelog file.

Thanks.

**Comment by jasminSPC** [comment]
There you go https://github.com/profitbricks/profitbricks-cli/releases/tag/1.2.5
