### ISSUE TITLE
Miss parameter 'name' for IP block

### ISSUE THREAD

**Issue by Sebi94nbg** [profitbricks/profitbricks-cli#44]
It's currently not possible to specify the name of a new IP block.
`$ profitbricks ipblock create --location [location] --size [size]`
This results, that new IP blocks always have the same name (schema) like this example: _IP\_BLOCK\_1457953551678_

Could you please add a further parameter?
`$ profitbricks ipblock create --location [location] --size [size] --name [name]`
Thanks!

**Comment by jasminSPC** [comment]
https://github.com/profitbricks/profitbricks-cli/releases/tag/1.2.6

**Comment by Sebi94nbg** [comment]
Great, thanks!

Don't forget to update it in the [README.md](https://github.com/profitbricks/profitbricks-cli/blob/master/README.md). ;)

**Comment by jasminSPC** [comment]
https://github.com/profitbricks/profitbricks-cli/pull/47/commits/1623ae6e5c487690d1c2aa5f618a97b31f2c86c9
