### ISSUE TITLE
ProfitBricks CLI running under scheduled task

### ISSUE THREAD

**Issue by k3n85** [profitbricks/profitbricks-cli#49]
I've been working the the CLI in order to automate the allocation of our VM's and while all the commands so far appear to be working just fine, I'm running into an issue while scheduling some of the  tasks. Because the CLI set up creates the .auth file in the users home directory, it appears that if you create a scheduled task to run under that same users context, it will not be able to reference the ProfitBricks CLI/Module and/or the .auth file, which causes the command to not be successful.

Is there anyway to call the CLI or reference the authentication file another way?

**Comment by edevenport** [comment]
Hello @k3n85 - I'm not sure I understand. You should be able to run the `profitbricks` CLI from any location as long as the `.auth` file is in the home directory of the user running the command. Can you provide an example of the error(s) you are receiving?

**Comment by k3n85** [comment]
I currently have a scheduled task (running as domain\admin) which has the .auth file generated and working while I am logged in (start/stop commands work fine). If I schedule to bat file with the start command, then log off, I get the following error in the logging (start.bat > log.txt 2>&1):

C:\Windows\system32>profitbricks server start --datacenterid 9a599a02-bad0-4a09-8fd6-d49105593a77 -i b1f8c21b-3924-4162-8270-4aef49fa5ec3 
'profitbricks' is not recognized as an internal or external command,
operable program or batch file.

C:\Windows\system32>END
'END' is not recognized as an internal or external command,
operable program or batch file.

My thought it something to do with the scheduled task not being able to see certain Env. Variables.

User Env Var for PATH: C:\Users\Administrator\AppData\Roaming\npm
System Var for PATH: %SystemRoot%\system32;%SystemRoot%;%SystemRoot%\System32\Wbem;%SYSTEMROOT%\System32\WindowsPowerShell\v1.0\;C:\Program Files\nodejs\;C:\Program Files (x86)\PuTTY\

Thoughts?

**Comment by k3n85** [comment]
Looks like I may have found the issue, after adding "C:\Users\Administrator\AppData\Roaming\npm" into the "System Environment Variables" PATH, the task was able to complete successfully even though the task is scheduled under a user, not system.
![schdtask_pb](https://cloud.githubusercontent.com/assets/656160/16820763/534564f0-4918-11e6-8982-f16e1d0289f3.jpg)
