### ISSUE TITLE
Confirm resource name when removing a resource

### ISSUE THREAD

**Issue by edevenport** [profitbricks/profitbricks-cli#51]
When you delete a resource, such as a datacenter, the UUID must be specified. It could be beneficial to print the resource name in the confirmation message. This would prevent accidental deletion if supplying the wrong UUID.

    $ profitbricks datacenter delete -id ac7610c3-e593-410d-95a2-ce44bd0db741
    You are about to delete a data center. Do you want to proceed? (y/n
    prompt: yes:

An example would be, 'You are about to delete the data center "My Datacenter". Do you want to proceed?'

I understand that this will require a GET request to retrieve the name, but I think this provides some extra protection to a potentially destructive command.

Also, the a closing parenthesis after "y/n" seems to be missing?

**Comment by jasminSPC** [comment]
Addressed with the fix for #52
