### ISSUE TITLE
Confirmation prompt is misleading

### ISSUE THREAD

**Issue by edevenport** [profitbricks/profitbricks-cli#52]
When I attempt to delete a resource (datacenter in this case), the **yes:** following the confirmation prompt would indicate that the default response will be "yes" if I press enter with no further input. However, this does not seem to be the case. Hitting enter results in no action - so the default seems to be "no".

The **yes** should be replaced with **no**. This should lead to less confusion.

    $ profitbricks datacenter delete -i d371dcb2-7277-4160-8bef-74f59e305659
    You are about to delete a data center. Do you want to proceed? (y/n
    prompt: yes:

    $ profitbricks datacenter delete -i d371dcb2-7277-4160-8bef-74f59e305659
    You are about to delete a data center. Do you want to proceed? (y/n
    prompt: yes:
    
    $ profitbricks datacenter delete -i d371dcb2-7277-4160-8bef-74f59e305659
    You are about to delete a data center. Do you want to proceed? (y/n
    prompt: yes: yes
    yes
    $ profitbricks datacenter delete -i d371dcb2-7277-4160-8bef-74f59e305659
    You are about to delete a data center. Do you want to proceed? (y/n
    prompt: yes:  yes
    yes
    { errorcode: 404,
      errormsg: '{\n  "httpStatus" : 404,\n  "messages" : [ {\n    "errorCode" : "309",\n    "message" : "Resource does not exist"\n  } ]\n}\n' }

**Comment by jasminSPC** [comment]
I've improved it with the following

You can pass 'yes'
```
$ profitbricks nic delete --datacenterid d3b1a39e-59be-4e1b-88d7-51828052493f  --serverid 2493d7ca-bb8b-4eda-8698-4a9e12541eb8 -i 5e5f0589-575c-4012-a690-934b7c874511
You are about to delete "null" NIC. Do you want to proceed? (y/n)
prompt: yes:  yes
RequestID: f30d1abc-aecd-4287-97b0-6cba5f66dc58
```

Or you can just hit enter:
```
$profitbricks loadbalancer delete --datacenterid d3b1a39e-59be-4e1b-88d7-51828052493f  --serverid 2493d7ca-bb8b-4eda-8698-4a9e12541eb8 -i ae2d212f-f8a2-4547-9a2c-19992fc299f2 
You are about to delete "null" Loadbalancer. Do you want to proceed? (y/n)
prompt: yes:  
RequestID: 6d7fa0be-6c6b-41da-b80c-9ac8d20007f3
```

I print the name of the object that is to be deleted. I've also added RequestId for when object is being deleted.
And then there is this:
```
$ profitbricks loadbalancer delete --datacenterid d3b1a39e-59be-4e1b-88d7-51828052493f  --serverid 2493d7ca-bb8b-4eda-8698-4a9e12541eb8 -i ae2d212f-f8a2-4547-9a2c-19992fc299f2 
Object you are trying to delete does not exist
```
When you try to remove object that doesn't exist the CLI will return the message above.
