### ISSUE TITLE
Feature Request: Add a failover group to lan object

### ISSUE THREAD

**Issue by angrox** [profitbricks/profitbricks-cli#56]
It should be possible to add a failover group via CLI (and API and subsequently the terraform profitbricks provider) to a LAN object. By now afaik it is only possible to do this via the GUI (Select LAN -> Select Failover Group -> Add new failover group)

**Comment by jasminSPC** [comment]
Currently Cloud API doesn't support failover groups for LAN.

Jasmin Gacić

**Comment by angrox** [comment]
Thanks for the answer! Is it planned for a future release? Would be awesome!

**Comment by edevenport** [comment]
@angrox The latest Cloud API v4 now supports IP failover groups and we are currently going through the existing SDKs and adding the new v4 features (IP failover, user management, image aliases, and contract resources). The underlying NodeJS SDK has been updated already to v4 and we should be updating the CLI in the next few weeks.

**Comment by nurfet-becirevic** [comment]
@angrox, version 4.1.0 was released today and includes the Cloud API v4 features and bug fixes.

**Comment by angrox** [comment]
Thanks! I will check asap. Closing this issue.
