### ISSUE TITLE
visibility into asyn requests

### ISSUE THREAD

**Issue by ambled** [profitbricks/profitbricks-cli#6]
I don't seem to find a flag to expose the resulting request_id from my commands so I can monitor the status of the action with curl.

it would also be helpful to have a requests command to avoid having to use curl to check the status of the requests as well since the authorization information is configured for the cli tool.

**Comment by jasminSPC** [comment]
This has been implemented and it is available in the latest release 1.1.1.
Thanks for the suggestion

**Comment by Sebi94nbg** [comment]
@jasminSPC I believe, you should close this issue, cause it has been solved. :)
