### ISSUE TITLE
Failure to load snapshot list (possibly more) with NodeJS >= 8.1

### ISSUE THREAD

**Issue by vain** [profitbricks/profitbricks-cli#60]
Calling `profitbricks snapshot list` simply yields an empty output when using NodeJS 8.1. Worked fine with previous versions of NodeJS.

Let me know if you can't reproduce this and/or if you need more information to debug.

**Comment by vain** [comment]
Note: There might be more issues with recent versions of NodeJS. Didn't investigate further.

**Comment by edevenport** [comment]
Thank you for reporting the issue @vain 

I have merged a PR into master that should address this issue. A third-party module called console.table was being used to render the output as a table. It seems that NodeJS v8.x now reserves the console.table namespace. Though, it is now reserved, it's not actually used and simply returns undefined.

I was able to work around this by first deleting the internal module and overriding it with the third-party module. We should implement a better longterm solution, but this should correct the issue for now. Can you confirm? If everything is working as expected, then I can tag a release and push to NPM later today.

**Comment by edevenport** [comment]
I have been running the automated tests on both NodeJS v6.11.x and v8.1.2. Both are passing now so I went ahead and tagged release v3.1.0 and pushed to NPM. If you still encounter problems, please feel free to reopen this issue.

**Comment by vain** [comment]
Hi,

yes, works like a charm now.

Thank you!
