### ISSUE TITLE
Create Snapshot and set permission for a specific group

### ISSUE THREAD

**Issue by Sebi94nbg** [profitbricks/profitbricks-cli#69]
Hey,
Using the profitbricks-cli I can create snapshots.

Other users can't see these created snapshots by the profitbricks-cli, unfortunately.

Is there a way to grant full / all permissions on this new created snapshot to a specific permission group using the profitbricks-cli?

Is `share` the right way for me? https://github.com/profitbricks/profitbricks-cli#share

`$ profitbricks share add --groupid [groupid] --resourceid [resourceid] --editprivilege [boolean] --shareprivilege [boolean]`

**Comment by nurfet-becirevic** [comment]
Hey @Sebi94nbg 
That's right, shares are way to go.

**Comment by Sebi94nbg** [comment]
Thanks for the confirmation, @nurfet-becirevic !
