### ISSUE TITLE
Possibility to set or unset the gateway option from the webinterface for an existing and new server

### ISSUE THREAD

**Issue by Sebi94nbg** [profitbricks/profitbricks-cli#9]
I miss the option, where I can set or unset the option, if the Profitbricks gateway should be used or not. Is this option already available or is it missing? I can't find it.

Would be great, if you could add this feature like the this to *all* commands, which were associated with "profitbricks server" command - creating and updating:

        profitbricks server create --datacenterid [dcid] --cores 1 --name "Demo Server" --ram 256 --enable-gateway [true|false]
        profitbricks server update --datacenterid [dcid] -i [serverid] --cores 1 --name "Demo Server" --ram 1024 --enable-gateway [true|false]

**Comment by jasminSPC** [comment]
Similar question to this one:
https://github.com/profitbricks/profitbricks-cli/issues/8

**Comment by Sebi94nbg** [comment]
Yes, it's a similar question, because it's also a network based question, but it's an other question...

**Comment by edevenport** [comment]
@Sebi94nbg - When you say ProfitBricks gateway, do you mean public Internet access? This can only be set on the LAN (public: true|false) during LAN creation or update. The LAN update method was missing from the CLI, but @jasminSPC just released an update to the profitbricks-cli that corrects this. If you remove the NPM and install it again, you should retrieve the new version. The public LAN can be toggled using the following commands:

    profitbricks lan update --datacenterid [dcid] --public true -i 1
    profitbricks lan update --datacenterid [dcid] --public false -i 1

In this case, `1` is the LAN ID I used for testing.

**Comment by Sebi94nbg** [comment]
@edevenport In the Profitbricks DCD, you can configure NICs for every server and there you have the possibility to check or uncheck the Profitbricks gatway. This box is checked by default and I need it unchecked due I have an own gateway as well as an own DHCP server.

http://i.imgur.com/rg4EcI3.png

**Comment by jasminSPC** [comment]
This can be achieved by passing dhcp parameter

 profitbricks nic update -i [nicid] --datacenterid [dcid] --serverid [serverid] --name [name] --ip [ip] `--dhcp true|false` --lan [lan]

Before you proceed please update the cli `npm update -g profitbricks-cli` the version you are looking for is 1.1.5

**Comment by Sebi94nbg** [comment]
I've updated the profitbricks-cli with your command, but it's still on the version 1.1.1.

        # npm update -g profitbricks-cli 1.1.5
        npm http GET https://registry.npmjs.org/profitbricks-cli
        npm http 304 https://registry.npmjs.org/profitbricks-cli

        # profitbricks --version
        1.1.1

**Comment by jasminSPC** [comment]
You don't have to provide the version nr at the end. Just do

```# npm update -g profitbricks-cli```


If you wish to reach me directly you can do it via skype jasmin.gacic,
I'll be glad to help


On Tue, Dec 15, 2015 at 2:26 PM, TS3tools <notifications@github.com> wrote:

> I've updated the profitbricks-cli with your command, but it's still on the
> version 1.1.1.
>
>     # npm update -g profitbricks-cli 1.1.5
>     npm http GET https://registry.npmjs.org/profitbricks-cli
>     npm http 304 https://registry.npmjs.org/profitbricks-cli
>
>     # profitbricks --version
>     1.1.1
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/profitbricks/profitbricks-cli/issues/9#issuecomment-164764101>
> .
>



-- 
Jasmin Gacić

**Comment by Sebi94nbg** [comment]
Thx, works!

        # profitbricks nic create --datacenterid 545aa6cb-d4e4-4081-a3e3-2b16041be281 --serverid 6fb9e77e-f844-4964-aa2e-9b764f0747c9 --name "p-v00321-nic" --ip 10.40.1.80 --lan 1 --dhcp false --json
        [{"Id":"9e12000c-f074-4b4c-a087-1b6fc5ccec05","Name":"p-v00321-nic","Created":"2015-12-15T14:07:01Z","State":"BUSY","Lan":"1","Mac":null,"Ips":["10.40.1.90"]}]
        RequestID: 5b0b6fe3-aee7-4423-b493-528c9ebaec5e

#closed
